# Parameters
map_update_interval: 1.0
maxUrange: 16.0
sigma: 0.01
kernelSize: 1
lstep: 0.05
astep: 0.01
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.02
srt: 0.04
str: 0.02
stt: 0.04
linearUpdate: 0.2
angularUpdate: 0.5
temporalUpdate: 3.0
resampleThreshold: 0.1
particles: 6
xmin: -50.0
ymin: -50.0
xmax: 50.0
ymax: 50.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
minimumScore: 0.0

base_frame: base_link
odom_frame: odom
# map_frame: map
