# Parameters
map_update_interval: 0.5  # Decides time interval in which gmapping updates/publishes map
maxUrange: 100.0          # Maximum usable laser range (maxUrange<maxRange)
maxRange: 110.0           # Maximum theoretical range of laser
sigma: 0.01
kernelSize: 2
lstep: 0.01
astep: 0.01
iterations: 50
lsigma: 0.25
ogain: 3.0
lskip: 0
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.3
angularUpdate: 0.1
temporalUpdate: 3.0
resampleThreshold: 0.1
particles: 16             # Decides the value of neff. neff drops drastically on loop closure else remains almost equal to particles
xmin: -50.0
ymin: -50.0
xmax: 50.0
ymax: 50.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
minimumScore: 1.0

base_frame: base_link
odom_frame: odom
